MissionExpedition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls'))
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from mysite import views

app_name = 'mysite'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('<int:secretcode_id>/select', views.select, name='select'),
    path('<int:secretcode_id>/mission_map', views.mission_map, name='mission_map'),
    path('<int:secretcode_id>/mission_quiz', views.mission_quiz, name='mission_quiz'),
    path('api_quiz', views.api_quiz, name='api_quiz'),
    path('<int:secretcode_id>/api_save_mission', views.api_save_mission, name='api_save_mission'),
    path('<int:secretcode_id>/api_save_quizs', views.api_save_quizs, name='api_save_quizs'),
    path('<int:secretcode_id>/api_save_words', views.api_save_words, name='api_save_words'),
    path('<int:secretcode_id>/api_save_mission_map', views.api_save_mission_map, name='api_save_mission_map'),
    path('<int:secretcode_id>/api_reset_mission_map', views.api_reset_mission_map, name='api_reset_mission_map'),
    path('map_test', views.map_test, name='map_test'),
]

mysite/models.py
from django.db import models
from mysite.values import Values
# Create your models here.


class SecretCode(models.Model):

    code = models.CharField('시크릿코드', max_length=10)
    desc = models.CharField('설명', max_length=250)

    def __str__(self):
        return self.desc

    def save(self, *args, **kwargs):
        super(SecretCode, self).save(*args, **kwargs)

        mq = MissionQuiz(secret_code_id=self.id)
        mq.mission_quiz_title = '미션퀴즈제목 : {} 의 미션퀴즈입니다.'.format(self.desc)
        mq.bomb_command_location = Values.bomb_command_location
        mq.mugunghwa_command_location = Values.mugunghwa_command_location
        mq.save()

        ml = MissionLocation(secret_code_id=self.id)
        ml.mission_loc_title = '미션위치제목 : {} 의 미션위치입니다.'.format(self.desc)
        ml.save()

        for quiz in Values.quizs:
            q = Quiz(mission_quiz_id=mq.id)
            q.quiz_no = quiz['quiz_no']
            q.quiz = quiz['quiz']
            q.quiz_answer = quiz['answer']
            q.quiz_wrong_answer1 = quiz['answer_w1']
            q.quiz_wrong_answer2 = quiz['answer_w2']
            q.save()

        for word in Values.words:
            m = MatchFinalWordMission(mission_quiz_id=mq.id)
            m.word = word
            m.save()


class MissionQuiz(models.Model):
    secret_code = models.ForeignKey(SecretCode, on_delete=models.CASCADE)
    mission_quiz_title = models.CharField('미션퀴즈제목', max_length=150, blank=True, null=True, default='')
    bomb_command_location = models.CharField('폭탄해제 지령 위치', max_length=500)          #폭탄해제 지령 위치
    mugunghwa_command_location = models.CharField('무궁화 지령 위치', max_length=500)       #무궁화 지령 위치

    def __str__(self):
        return self.mission_quiz_title

    def save(self, *args, **kwargs):
        super(MissionQuiz, self).save(*args, **kwargs)

    no = 2

    def get_no(self):
        self.no = self.no + 1
        return self.no


class Quiz(models.Model):   #퀴즈는 7개까지 입력가능하도록 한다.
    mission_quiz = models.ForeignKey(MissionQuiz, on_delete=models.CASCADE)

    quiz_no = models.IntegerField('퀴즈번호', null=True)
    quiz = models.CharField('퀴즈질문', max_length=500)
    quiz_answer = models.CharField('퀴즈정답', max_length=100)
    quiz_wrong_answer1 = models.CharField('퀴즈오답1', max_length=100)
    quiz_wrong_answer2 = models.CharField('퀴즈오답2', max_length=100)


class MatchFinalWordMission(models.Model):  #단어는 7개까지 입력가능하도록 한다.
    mission_quiz = models.ForeignKey(MissionQuiz, on_delete=models.CASCADE)
    word = models.CharField('미션단어', max_length=50)


class MissionLocation(models.Model):
    mission_loc_title = models.CharField('미션위치제목', max_length=150, null=True, default='')
    secret_code = models.ForeignKey(SecretCode, on_delete=models.CASCADE)

    loc_mission1_gps_lat = models.CharField(max_length=20, null=True, default="0")
    loc_mission1_gps_lng = models.CharField(max_length=20, null=True, default="0")

    loc_mission2_gps_lat = models.CharField(max_length=20, null=True, default="0")
    loc_mission2_gps_lng = models.CharField(max_length=20, null=True, default="0")

    loc_mission3_gps_lat = models.CharField(max_length=20, null=True, default="0")
    loc_mission3_gps_lng = models.CharField(max_length=20, null=True, default="0")

    loc_mission4_gps_lat = models.CharField(max_length=20, null=True, default="0")
    loc_mission4_gps_lng = models.CharField(max_length=20, null=True, default="0")

    def __str__(self):
        return self.mission_loc_title

mysite/views.py
import logging

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

from django.urls import reverse
from mysite.models import *
from mysite.values import *


logger = logging.getLogger('mylogger')

# Create your views here.


def index(request):

    return render(request, 'mysite/index.html')


def login(request):

    try:
        secrectcode_info = SecretCode.objects.get(code=request.POST['code'])

    except(KeyError, SecretCode.DoesNotExist):

        return render(request, 'mysite/index.html',{
            'error_message': "없는 비밀코드 입니다. 관리자에게 문의해주세요.",
        })
    else:
        request.session['secretcode_code'] = secrectcode_info.code
        return HttpResponseRedirect(reverse('mysite:select', args=(secrectcode_info.pk,)))

def logout(request):
    try:
        del request.session['secretcode_code']
    except KeyError:
        pass
    return render(request, 'mysite/index.html')

def select(request, secretcode_id):
    print(request.session['secretcode_code'])
    if 'secretcode_code' not in request.session:
        return render(request, 'mysite/index.html')

    return render(request, 'mysite/select.html', {
        'secretcode_id': secretcode_id,
        'secretcode_code': request.session['secretcode_code'],
    })


def mission_map(request, secretcode_id):
    if 'secretcode_code' not in request.session:
        return render(request, 'mysite/index.html')

    mp = get_object_or_404(MissionLocation, secret_code_id=secretcode_id)

    if mp.loc_mission1_gps_lat == "0":
        btnStyle1 = "primary"
    else:
        btnStyle1 = "success"

    if mp.loc_mission2_gps_lat == "0":
        btnStyle2 = "primary"
    else:
        btnStyle2 = "success"

    if mp.loc_mission3_gps_lat == "0":
        btnStyle3 = "primary"
    else:
        btnStyle3 = "success"

    if mp.loc_mission4_gps_lat == "0":
        btnStyle4 = "primary"
    else:
        btnStyle4 = "success"

    btnStyle = {'btnStyle1':btnStyle1, 'btnStyle2':btnStyle2, 'btnStyle3':btnStyle3, 'btnStyle4':btnStyle4}

    return render(request, 'mysite/mission_map.html', {'secretcode_id':secretcode_id, 'mission_map':mp, 'btnStyle':btnStyle})



def api_save_mission_map(request, secretcode_id):

    mission_loc = get_object_or_404(MissionLocation, secret_code_id=secretcode_id)

    if request.POST['GPS_N'] == "1":
        mission_loc.loc_mission1_gps_lng = request.POST['GPS_LNG']
        mission_loc.loc_mission1_gps_lat = request.POST['GPS_LAT']
    elif request.POST['GPS_N'] == "2":
        mission_loc.loc_mission2_gps_lng = request.POST['GPS_LNG']
        mission_loc.loc_mission2_gps_lat = request.POST['GPS_LAT']
    elif request.POST['GPS_N'] == "3":
        mission_loc.loc_mission3_gps_lng = request.POST['GPS_LNG']
        mission_loc.loc_mission3_gps_lat = request.POST['GPS_LAT']
    elif request.POST['GPS_N'] == "4":
        mission_loc.loc_mission4_gps_lng = request.POST['GPS_LNG']
        mission_loc.loc_mission4_gps_lat = request.POST['GPS_LAT']

    mission_loc.save()

    return HttpResponse("OK")


def api_reset_mission_map(request, secretcode_id):
    mission_loc = get_object_or_404(MissionLocation, secret_code_id=secretcode_id)

    mission_loc.loc_mission1_gps_lng = "0"
    mission_loc.loc_mission1_gps_lat = "0"
    mission_loc.loc_mission2_gps_lng = "0"
    mission_loc.loc_mission2_gps_lat = "0"
    mission_loc.loc_mission3_gps_lng = "0"
    mission_loc.loc_mission3_gps_lat = "0"
    mission_loc.loc_mission4_gps_lng = "0"
    mission_loc.loc_mission4_gps_lat = "0"

    mission_loc.save()

    return HttpResponse("OK")


def mission_quiz(request, secretcode_id):
    if 'secretcode_code' not in request.session:
        return render(request, 'mysite/index.html')

    mq = get_object_or_404(MissionQuiz, secret_code_id=secretcode_id)
    q = Quiz.objects.filter(mission_quiz_id=mq.id)
    w = MatchFinalWordMission.objects.filter(mission_quiz_id=mq.id)

    return render(request, 'mysite/mission_quiz.html', {'secretcode_id':secretcode_id, 'mission_quiz': mq, 'values': Values})


def api_quiz(request):
    for quiz in Values.quizs:
        if(quiz['quiz_no'] == request.GET['quiz_no']):
            quiz_s = quiz
            break

    return JsonResponse(quiz_s, safe=False)


def api_save_mission(request, secretcode_id):
    mission = get_object_or_404(MissionQuiz, secret_code_id=secretcode_id)

    if request.POST['TYPE'] == "B":
        mission.bomb_command_location = request.POST['bomb_command_location']

    if request.POST['TYPE'] == "M":
        mission.mugunghwa_command_location = request.POST['mugunghwa_command_location']

    mission.save()

    return HttpResponse("OK")


def api_save_quizs(request, secretcode_id):
    mission = get_object_or_404(MissionQuiz, secret_code_id=secretcode_id)
    quiz = mission.quiz_set.get(quiz_no=int(request.POST['quiz_no']))

    quiz.quiz = request.POST['question']
    quiz.quiz_answer = request.POST['answer']
    quiz.quiz_wrong_answer1 = request.POST['quiz-wrong-answer1']
    quiz.quiz_wrong_answer2 = request.POST['quiz-wrong-answer2']

    quiz.save()

    return HttpResponse("OK")


def api_save_words(request, secretcode_id):
    mission = get_object_or_404(MissionQuiz, secret_code_id=secretcode_id)

    for w in str(request.POST["wordlist"])[:-1].split(','):
        pk, w = w.split('|')
        word = mission.matchfinalwordmission_set.get(pk=int(pk))
        word.word = w
        word.save()

    return HttpResponse("OK")


def map_test(request):
    return render(request, 'mysite/map_test.html')

mysite/templates/mysite/index.html
{%  extends "base.html" %}

{% block title %} 보물찾기 관리자 {% endblock %}

{%  block content %}
          <div style="height: 50px"></div>
        <h1 style="text-align: center">보물섬 관리자</h1>
          <div style="height: 50px"></div>
        <form action="{%  url 'mysite:login'  %}" method="post">
            {%  csrf_token %}
            <input type="text" name="code" id="code" class="form-control"  placeholder="비밀코드를 입력하세요.">
            <br>
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="확인" />
        </form>
	{% if error_message %}
		<br><br>
	<p style="text-align: center;color: red;"><strong>{{ error_message }}</strong></p>
	{% endif %}
{%  endblock %}

mysite/templates/mysite/map_test.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>
<script>
	// check for Geolocation support
if (navigator.geolocation) {
  console.log('Geolocation is supported!');
}
else {
  console.log('Geolocation is not supported for this Browser/OS.');
}

window.onload = function() {
  var startPos;
  var geoSuccess = function(position) {
    startPos = position;
    //document.getElementById('startLat').innerHTML = startPos.coords.latitude;
    //document.getElementById('startLon').innerHTML = startPos.coords.longitude;
	  console.log(startPos);
  };
  navigator.geolocation.getCurrentPosition(geoSuccess);
};

</script>
</body>
</html>

mysite/templates/mysite/mission_quiz.html
{%  extends "base.html" %}

{% block title %} 보물찾기 텍스트설정 {% endblock %}

{%  block content %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link " href="{% url 'mysite:select' secretcode_id %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'mysite:mission_map' secretcode_id %}">Map</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Quiz</a>
  </li>
</ul>

<div id="content"  class="container">



<div class="alert alert-primary" role="alert">
    <h5>미션 및 퀴즈 관련 텍스트 설정</h5>
</div>
<form>
<ul class="list-group">
    <li class="list-group-item">
      <div class="form-group">
        <label for="exampleFormControlTextarea1">1.폭탄해제 지령 위치</label>
          <button type="button" id="btnInitBomMission" class="btn btn-primary btn-sm">기본값</button>
          <button type="button" id="btnSaveBomMission" class="btn btn-primary btn-sm">전송</button>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3">{{ mission_quiz.bomb_command_location }}</textarea>
      </div>
    </li>
    <li class="list-group-item">
      <div class="form-group">
        <label for="exampleFormControlTextarea1">2. 무궁화미션 지령 위치</label>
          <button type="button" id="btnInitMugunghwaMission" class="btn btn-primary  btn-sm">기본값</button>
          <button type="button" id="btnSaveMugunghwaMission" class="btn btn-primary btn-sm">전송</button>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3">{{ mission_quiz.mugunghwa_command_location }}</textarea>
      </div>
    </li>


    {% for quiz in mission_quiz.quiz_set.all %}

    <li class="list-group-item list-group-item-info">
      <div class="form-group">
        <label for="exampleFormControlTextarea1">{{ mission_quiz.get_no }}. 퀴즈{{ quiz.quiz_no }} 문제</label>
          <button type="button" class="btnInitQuiz btn btn-primary btn-sm" q_no="{{ quiz.quiz_no }}">기본값</button>
          <button type="button" class="btnSaveQuiz btn btn-primary btn-sm" q_no="{{ quiz.quiz_no }}">전송</button>
          <textarea class="quiz-question form-control" id="exampleFormControlTextarea1" rows="3">{{ quiz.quiz }}</textarea>
          <label for="exampleFormControlTextarea1"> 퀴즈{{ forloop.counter }} 정답</label>
          <input type="text" class="quiz-answer form-control" value="{{ quiz.quiz_answer }}">
          <label for="exampleFormControlTextarea1" >퀴즈{{ forloop.counter }} 오답</label>
          <input type="text" class="quiz-wrong-answer1 form-control" value="{{ quiz.quiz_wrong_answer1 }}">
          <label for="exampleFormControlTextarea1"> 퀴즈{{ forloop.counter }} 오답</label>
          <input type="text" class="quiz-wrong-answer2 form-control" value="{{ quiz.quiz_wrong_answer2 }}">
      </div>
    </li>
    {% endfor %}

    <li class="list-group-item list-group-item-primary">
<div class="form-group">
    <label for="exampleFormControlTextarea1">10. 최종 단어 맞추기 미션</label>
      <button type="button" id="btnInitWord" class="btn btn-primary btn-sm">기본값</button>
      <button type="button" id="btnSaveWord" class="btn btn-primary btn-sm">전송</button>
    <div class="row">
        {% for mf_word in mission_quiz.matchfinalwordmission_set.all %}
        <div><input type="text" class="word form-control" value="{{ mf_word.word }}" maxlength="3" size="6" word_pk="{{ mf_word.pk }}"></div>
        {% endfor %}
    </div>

  </div>
    </li>
</ul>
</form>


{%  endblock %}
</div>

{% block jsScript %}
<script>
   $(document).ready(function(){

       //폭탄해체 지령 위치 초기화
       $("#btnInitBomMission").click(function () {
            $(this).siblings("textarea").val("{{ values.bomb_command_location }}");
       });

       //무궁화미션 지령 위치 초기화
       $("#btnInitMugunghwaMission").click(function () {
            $(this).siblings("textarea").val("{{ values.mugunghwa_command_location }}");
       });
        //퀴즈 초기화
       $(".btnInitQuiz").click(function(){
            //alert($(this).attr('q_no'));
            var q_no = $(this).attr('q_no');
            var obj = $(this);

            $.ajax({
                type: "GET",
                url: "{% url 'mysite:api_quiz' %}",
                data: {'quiz_no':q_no,  'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: "json",
            }).done(function (data) {
                obj.siblings('.quiz-question').val(data['quiz']);
                obj.siblings('.quiz-answer').val(data['answer']);
                obj.siblings('.quiz-wrong-answer1').val(data['answer_w1']);
                obj.siblings('.quiz-wrong-answer2').val(data['answer_w2']);
            }).fail(function () {

            });
       });
       //단어 초기화
       $("#btnInitWord").click(function () {
           var words = '{{ values.get_words }}'.split('|');
           var i=0;
           $(".word").each(function () {
               $(this).val(words[i]);
               i++;
           });
       });

       //폭탄해체 지령 위치 저장
       $("#btnSaveBomMission").click(function () {
            console.log($(this).siblings("textarea").val());
            $.ajax({
                type: "POST",
                url: "{% url 'mysite:api_save_mission' mission_quiz.secret_code_id %}",
                data: {"TYPE":"B", "bomb_command_location":$(this).siblings("textarea").val(), 'csrfmiddlewaretoken': '{{ csrf_token }}'}
            }).done(function (data) {

            }).fail(function () {

            })
       });

       //무궁화미션 지령 위치 저장
       $("#btnSaveMugunghwaMission").click(function () {
            console.log($(this).siblings("textarea").val());
            $.ajax({
                type: "POST",
                url: "{% url 'mysite:api_save_mission' mission_quiz.secret_code_id %}",
                data: {"TYPE":"M", "mugunghwa_command_location":$(this).siblings("textarea").val(), 'csrfmiddlewaretoken': '{{ csrf_token }}'}
            }).done(function (data) {

            }).fail(function () {

            })
       });

       //퀴즈 저장
       $(".btnSaveQuiz").click(function () {
           var obj = $(this);
           var d = {
                'quiz_no':obj.attr('q_no'),
                'question':obj.siblings('.quiz-question').val(),
                'answer':obj.siblings('.quiz-answer').val(),
                'quiz-wrong-answer1':obj.siblings('.quiz-wrong-answer1').val(),
                'quiz-wrong-answer2':obj.siblings('.quiz-wrong-answer2').val(),
                'csrfmiddlewaretoken': '{{ csrf_token }}'
           }

           $.ajax({
                type: "POST",
                url: "{% url 'mysite:api_save_quizs' mission_quiz.secret_code_id %}",
                data: d
           }).done(function (data) {

           }).fail(function () {

           })
       });

       //단어 저장
       $("#btnSaveWord").click(function () {
           var obj = $(this);
           var wordlist = "";
           $(".word").each(function () {
                wordlist = wordlist + $(this).attr("word_pk") + "|" + $(this).val() + ",";
           });

           var d = {
               "wordlist":wordlist,
               'csrfmiddlewaretoken': '{{ csrf_token }}'
           };

           $.ajax({
                type: "POST",
                url: "{% url 'mysite:api_save_words' mission_quiz.secret_code_id %}",
                data: d,
           }).done(function (data) {

           }).fail(function () {

           })
       });


   });
</script>
{% endblock %}

mysite/templates/mysite/select.html
{%  extends "base.html" %}

{% block title %} 보물찾기 관리자 {% endblock %}

{%  block content %}
	<div style="margin: 10px;">

			<h2 style="text-align: center">
			보물 찾기 관리자
			</h2>
	</div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-5">
        <div class="row" style="height: 20px;"></div>
        <div class="row">
            <a href="{%  url 'mysite:mission_map' secretcode_id  %}" class="btn btn-primary btn-lg btn-block"><p>위치</p><p>설정</p></a>
        </div>
        <div class="row" style="height: 10px;"></div>
        <div class="row">
            <a href="{%  url 'mysite:mission_quiz' secretcode_id %}" class="btn btn-primary btn-lg btn-block"><p>텍스트</p><p>설정</p></a>
        </div>
    </div>
    <div class="col">

    </div>
  </div>
	<div style="margin: 10px;">
			<p style="text-align: center">
			현재 비밀코드 : {{ secretcode_code }} 로 로그인되어 있습니다.
			</p>
			 <a href="{%  url 'mysite:logout' %}" class="btn btn-warning btn-lg btn-block">Logout 하기</a>
	</div>
{% endblock %}